"""
Data models and schemas for Mattermost entities.

This module contains Pydantic models for all Mattermost data structures
including channels, posts, users, reactions, and configuration.
"""

# Base models and common types
from .base import (
    ErrorResponse,
    MattermostBase,
    MattermostResponse,
    StatusOK,
)

# Authentication and session models
from .auth import (
    AccessToken,
    AccessTokenRequest,
    AuthTestRequest,
    ChangePasswordRequest,
    LdapSyncRequest,
    LoginRequest,
    LoginResponse,
    LogoutRequest,
    MfaSetupRequest,
    MfaUpdateRequest,
    OAuthApp,
    OAuthAppRequest,
    OAuthAuthorizeRequest,
    OAuthTokenRequest,
    OAuthTokenResponse,
    PasswordResetComplete,
    PasswordResetRequest,
    RevokeAllSessionsRequest,
    RevokeSessionRequest,
    SamlCertificateRequest,
    SamlRequest,
    Session,
)

# Channel models
from .channels import (
    Channel,
    ChannelCreate,
    ChannelData,
    ChannelList,
    ChannelMember,
    ChannelMemberPatch,
    ChannelMembersGetByIds,
    ChannelMemberWithTeamData,
    ChannelNotifyProps,
    ChannelPatch,
    ChannelSearch,
    ChannelStats,
    ChannelUnread,
)

# Post models
from .posts import (
    Emoji,
    FileInfo,
    OpenGraph,
    OpenGraphAudio,
    OpenGraphImage,
    OpenGraphVideo,
    Post,
    PostAction,
    PostCreate,
    PostList,
    PostListWithSearchMatches,
    PostMetadata,
    PostPatch,
    PostSearch,
    Reaction,
    SlackAttachment,
    SlackAttachmentField,
)

# Team models
from .teams import (
    Team,
    TeamCreate,
    TeamExists,
    TeamInvite,
    TeamMap,
    TeamMember,
    TeamMembersGetByIds,
    TeamMemberWithTeam,
    TeamPatch,
    TeamSearch,
    TeamStats,
    TeamUnread,
)

# User models
from .users import (
    Timezone,
    User,
    UserAuthData,
    UserAutocomplete,
    UserAutocompleteInChannel,
    UserAutocompleteInTeam,
    UserCreate,
    UserLogin,
    UserNotifyProps,
    UserPatch,
    UsersStats,
)

# Webhook and integration models
from .webhooks import (
    Bot,
    BotPatch,
    BotRequest,
    Command,
    CommandRequest,
    CommandResponse,
    DialogRequest,
    DialogResponse,
    IncomingWebhook,
    IncomingWebhookRequest,
    IntegrationAction,
    MessageAttachment,
    OutgoingWebhook,
    OutgoingWebhookRequest,
    PostActionIntegrationRequest,
    PostActionIntegrationResponse,
    WebhookPayload,
)

__all__ = [
    # Base models
    "MattermostBase",
    "MattermostResponse",
    "StatusOK",
    "ErrorResponse",
    # Authentication
    "Session",
    "LoginRequest",
    "LoginResponse",
    "LogoutRequest",
    "AccessToken",
    "AccessTokenRequest",
    "RevokeSessionRequest",
    "RevokeAllSessionsRequest",
    "PasswordResetRequest",
    "PasswordResetComplete",
    "ChangePasswordRequest",
    "MfaSetupRequest",
    "MfaUpdateRequest",
    "OAuthApp",
    "OAuthAppRequest",
    "OAuthAuthorizeRequest",
    "OAuthTokenRequest",
    "OAuthTokenResponse",
    "SamlRequest",
    "LdapSyncRequest",
    "SamlCertificateRequest",
    "AuthTestRequest",
    # Users
    "User",
    "UserCreate",
    "UserPatch",
    "UserLogin",
    "UserAuthData",
    "UserNotifyProps",
    "UserAutocomplete",
    "UserAutocompleteInTeam",
    "UserAutocompleteInChannel",
    "UsersStats",
    "Timezone",
    # Teams
    "Team",
    "TeamCreate",
    "TeamPatch",
    "TeamMember",
    "TeamMemberWithTeam",
    "TeamStats",
    "TeamExists",
    "TeamUnread",
    "TeamInvite",
    "TeamMap",
    "TeamSearch",
    "TeamMembersGetByIds",
    # Channels
    "Channel",
    "ChannelCreate",
    "ChannelPatch",
    "ChannelMember",
    "ChannelMemberWithTeamData",
    "ChannelMemberPatch",
    "ChannelData",
    "ChannelStats",
    "ChannelUnread",
    "ChannelNotifyProps",
    "ChannelSearch",
    "ChannelMembersGetByIds",
    "ChannelList",
    # Posts
    "Post",
    "PostCreate",
    "PostPatch",
    "PostList",
    "PostListWithSearchMatches",
    "PostSearch",
    "PostAction",
    "PostMetadata",
    "Reaction",
    "FileInfo",
    "Emoji",
    "SlackAttachment",
    "SlackAttachmentField",
    "OpenGraph",
    "OpenGraphImage",
    "OpenGraphVideo",
    "OpenGraphAudio",
    # Webhooks and Integrations
    "IncomingWebhook",
    "IncomingWebhookRequest",
    "OutgoingWebhook",
    "OutgoingWebhookRequest",
    "Command",
    "CommandRequest",
    "CommandResponse",
    "Bot",
    "BotRequest",
    "BotPatch",
    "WebhookPayload",
    "IntegrationAction",
    "DialogRequest",
    "DialogResponse",
    "MessageAttachment",
    "PostActionIntegrationRequest",
    "PostActionIntegrationResponse",
]
